<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.3.2.min.js'); ?>

<h4>Sign up</h4>
<?php

if(isset($this->errorMessage)){
            echo '<div class="alert alert-error">'.$this->errorMessage.'</div>';

}?>
<?php
if(isset($this->success)){
          echo '<div class="alert alert-success">Succesfully sign up. <a href="'.$this->url(array('module'=>'default',
											'controller'=>'autentication',
											'action'=>'login')).'">Login</a></div>';
}?>
<?php
echo $this->regform;
?>